apiVersion: v1
kind: Pod
metadata:
  name: pod2-example
  namespace: default
  labels:
    quota.scheduling.koordinator.sh/name: "quota-child2"
spec:
  schedulerName: koord-scheduler
  containers:
  - command:
    - sleep
    - 5m
    image: busybox
    imagePullPolicy: IfNotPresent
    name: curlimage
    resources:
      limits:
        cpu: 40m
        memory: 30Mi
      requests:
        cpu: 40m
        memory: 30Mi
  restartPolicy: Never